### ISSUE TITLE
Bluetooth no audio and volume control over connected devices

### ISSUE THREAD

**Issue by mcdinner** [tdm/android_device_fxtec_pro1#13]
When connected to a Bluetooth audio device (headphones/car) no audio(music,call,notifications) output to that device does not work, also volume control over the device is not working. 

Other controls and functions like forward, reverse, play, pause and contact sharing do work.
I can provide logs if needed.

**Comment by tdm** [comment]
Please try test8.

**Comment by tdm** [comment]
Fixed per forum post.
