### ISSUE TITLE
[recovery] NanoDroid-setup can't write to /data/media/0

### ISSUE THREAD

**Issue by Loader009** [tdm/android_device_fxtec_pro1#15]
I guess this is a recovery bug, but I am not actually sure because I have never worked with LOS-recovery before.

If there is data in /data/media/0, the filenames/folders seem to be encrypted.
I think that NanoDroid tries to write some files there, but nothing appears even on a clean /data/media/0.

Configuring NanoDroid-setup to use /data instead works though.

I have no idea on how to log this, I haven't noticed relevant log entries for this (I tried a lot and the log was very long).

**Comment by tdm** [comment]
Lineage recovery does not decrypt data.  This is intentional.  Please use TWRP when a decrypting version is made available.
