### ISSUE TITLE
Issues with a custom build

### ISSUE THREAD

**Issue by Loader009** [tdm/android_device_fxtec_pro1#16]
I managed to do a build but some things are not working:
WiFi, Audio and maybe sim/baseband also, not tried it yet.

Changed nothing except for outcommenting the FMRadio app and applied that patch:
https://github.com/microg/android_packages_apps_GmsCore/blob/master/patches/android_frameworks_base-P.patch
Which has nothing to do with audio or wifi.

Did I miss some other repo, which is not in some dependency?

edit: If there is a way to get in touch directly (preferably telegram) with some dev/maintainer for this device, please let me know.
Then I might not need to always open an issue.

logcat of my build:
[adblogcat.log](https://github.com/tdm/android_device_fxtec_pro1/files/4112522/adblogcat.log)

**Comment by Gigadoc2** [comment]
I think it is known that wifi does not work, as @tdm just started with the custom vendor image.

**Comment by Loader009** [comment]
Ohm sorry... I probably didn't noticed that on his build >.<

**Comment by Gigadoc2** [comment]
No no, the last released build from him does *not* have the custom vendor image, that was added later. So if you build it now, it will have the custom vendor image, and thus have the known broken wifi and cell data ;)

**Comment by Loader009** [comment]
Ah, understood.
Let me know if I can help.
For now the Pro1 is only for testing, until LOS16 is stable and can be used as daily driver.

I have little knowledge with building ROMs, but that way I can quickly build and test changes.

**Comment by Gigadoc2** [comment]
Just for your information, if you want to have a build with your patches but using the stock vendor partition (so that Wifi, cell data and audio are as they were with the test2 build), just build with  `tdm/android_device_idealte_msm8998-common` at commit `262804a191600b9dd03f9bd8ef0b78e5dd440d57`, and fastboot flash the stock vendor image again.

I did so (+ incorporating mccrearys open merge requests) and to my surprise it works fine (except for, you know, tdms improvements to his vendor image) :)

**Comment by Loader009** [comment]
Yeah, thx.
I might do so for checking other bugs but not for daily driver. I had to wipe userdata in order to boot my build.

I have no idea, what tdms is. And I am not sure, where to get the stock vendor image for now. But I'll look tomorrow for it.

I can also host builds later, if others are excited to try it out. But a warning, that a wipe is necessary should be hang out.

**Comment by Gigadoc2** [comment]
I meant "tdms improvements" as the improvements that tdm has made to the vendor image :)

You can get the vendor boot image from https://community.fxtec.com/topic/2466-guide-restore-to-stock-firmware-using-fastboot-method/

If you switch ROMs you _always_ have to wipe, as at the very least the singing key changes. That also holds true if two different people build from the same source, unless they use the test keys.

**Comment by Loader009** [comment]
I'll close this issue, since there will be new builds and it seems that this three will be solved by then.

**Comment by dicer** [comment]
@Loader009 Would you be so kind to provide your local_manifest?

**Comment by Loader009** [comment]
@dicer there you go:
https://gist.github.com/Loader009/fddef1cb5c30a5d57c850bedce538dad
I am not sure if the last repo is needed, I could build without it some weeks ago, but I get errors without it.
