### ISSUE TITLE
Virtual keyboard doesn't come up when setting up Wifi on first start

### ISSUE THREAD

**Issue by CommanderStrax** [tdm/android_device_fxtec_pro1#17]
Hi,

just flashed version 3 and when trying to connect to my Wifi in the set-up screen/initialization screen the virtual keyboard won't come up when trying to enter the password. The issue also comes up when I need to confirm the PIN for the device or connect with my google account.

**Comment by EvilDragon** [comment]
That's probably a duplicate of:
https://github.com/tdm/android_device_fxtec_pro1/issues/5

**Comment by tdm** [comment]
Please try again with test7 or later and reply back.

**Comment by CommanderStrax** [comment]
Yeah if I double-click the textfield the virtual keyboard comes up. That is acceptable for me, thanks!
