### ISSUE TITLE
WPA Enterprise does not work

### ISSUE THREAD

**Issue by Gigadoc2** [tdm/android_device_fxtec_pro1#18]
I tried to connect to my local eduroam today, it does not work. Unfortunately I could not get any relevant logs with logcat either...

Not sure what the problem is here, and in lieu of log messages also not sure how do debug it. It's not the first time though that I've witnessed an Android phone having trouble with WPA Enterprise. My notebook, right next to the phone, could connect to the network, but it's also running iwd and not wpa_supplicant.

**Comment by tdm** [comment]
I don't know exactly what "WPA Enterprise" is.  And I'm afraid I don't have any way to test it, unless you can guide me through setting up an OpenWRT or similar with it.  So logs of a successful connection vs. failed connection are probably going to be needed.

Does this work on stock?

**Comment by jannoke** [comment]
WPA enterprise uses username and password to authenticate user to network. It uses radius backend to do so. This is actually broken on some android devices out of the box.

https://openwrt.org/docs/guide-user/network/wifi/wireless.security.8021x

Configuring openwrt router to run WPA-Enterprise is not that challenging task. Putting a radius server behind there to give sensible information is most of the work.

**Comment by Gigadoc2** [comment]
I have to apologize for this one, it just started working now. I am not even on the newest build, so I have no idea what changed, but it has nothing to do with this port I suppose.

I will close this issue for now, and _maybe_ reopen it if the behaviour stays flaky over long time periods with the current builds.

@jannoke: At some point in the past I have heard of setting up a "fakeradius" which allows arbitrary login information to connect. It was used to allow guests on a network to also have encrypted wifi, as opposed to completely unauthenticated and unencrypted wifi. However, I can't find anything about that anymore when searching for fakeradius. I am planning to set up 8021x at home anyway, so if this should become an issue again I might be able to provide logs from _both_ sides.
