### ISSUE TITLE
Physical Keyboard is always active

### ISSUE THREAD

**Issue by EvilDragon** [tdm/android_device_fxtec_pro1#19]
In the settings, you can setup that the Virtual Keyboard either only shows when the physical keyboard is not active (which is the default setting) or everytime.

On the stock image, that works well: When you slide out the physical keyboard, the virtual keyboard is not shown.

This doesn't work here. The virtual keyboard only pops up, when you set it to "Keep it on screen while physical keyboard is active".
So it seems that the physical keyboard is ALWAYS active. However, it should only be set to active when you slide it out.

**Comment by mccreary** [comment]
This sounds like a side-effect of change 9b42f622. Marking the keyboard as external disables the virtual keyboard, while if it is marked internal then Android will automatically display the virtual keyboard when the slide is closed.

FYI, this patch was a hack to enable wake on any keypress, but we didn't realize it causes this undesirable side-effect. Reverting 9b42f622 is probably the right choice.

**Comment by EskeRahn** [comment]
Most likely part of same issue:
It is possible to interact with the physical keyboard when the slider is closed.
(try with a toothpick touching space, and close the slider)

**Comment by cinaeco** [comment]
With test7, I now seem to see correct behaviour: the virtual keyboard appears when I want text entry and the device is closed, and it disappears when I open the slider. So far I have seen only one exception, that is Termux. For that app, I still need to set "Show virtual keyboard" in order to get a virtual keyboard.

**Comment by tdm** [comment]
Fixed in test7.
