### ISSUE TITLE
WiFi symbol in status bar is broken

### ISSUE THREAD

**Issue by steffenWi** [tdm/android_device_fxtec_pro1#2]
Even when standing next to a router the WiFi symbol is completely greyed out.

**Comment by EvilDragon** [comment]
I can confirm that, just wanted to add that this is ONLY an issue with the status bar symbol. Opening the Wifi settings properly shows the strength.

**Comment by tdm** [comment]
Should be fixed in test9.

**Comment by tdm** [comment]
No response, marking fixed.
