### ISSUE TITLE
Phone calls sometimes are muted when the screen switches off

### ISSUE THREAD

**Issue by EvilDragon** [tdm/android_device_fxtec_pro1#20]
I'm still trying to find out when exactly it happens, but it seems that is an issue at least every three or four phone calls:

When the screen switches off during the call, the phonecall is completely muted. You can't hear the other one and he can't hear you anymore. You can switch the screen back on with the power button which unmutes that - but a few seconds later, it will go black and muted again.

**Comment by tdm** [comment]
Please try again with test7 or later.

**Comment by tdm** [comment]
No reply after 7 days.
