### ISSUE TITLE
Phone calls can mess up audio it seems

### ISSUE THREAD

**Issue by EvilDragon** [tdm/android_device_fxtec_pro1#21]
Sometimes after finishing a phone call (I THINK it always happens after https://github.com/tdm/android_device_fxtec_pro1/issues/20 but this needs to be confirmed), it seems audio it total is messed up.

Playing any voice messages with WhatsApp doesn't work anymore, playing audio with DSub has a huge delay (audio starts randomly 5 - 15 seconds after having pushed the Play button) and DroidSound also doesn't play anymore music.

So far, I was only able to fix this using a reboot.

**Comment by tdm** [comment]
Please try again with test7 or later.
