### ISSUE TITLE
Accessing internal storage (/storage/emulated/0/) doesn't work reliable

### ISSUE THREAD

**Issue by EvilDragon** [tdm/android_device_fxtec_pro1#22]
This is a pretty weird one.
For some reason, the internal storage can't be accessed by some programs.
I can access it using a file manager, but Lightning (webbrowser) sometimes can't download anything to it (it doesn't show any error, but the downloaded file simply isn't there) and even the Alarm clock only played the default tune one time instead of the alarm sound I had on the internal storage.

I haven't found out WHEN this happens or WHY, but at least not being able to download files seems to happen pretty often.

Is there some security system that could prevent the download maybe?

**Comment by tdm** [comment]
I am not aware of any reason that internal storage would not work reliably.  It should either work or not, it should not be intermittent.

Is it possible your device has an unreliable flash chip?  Have you checked the kernel logs and the adb log to see if there are any clues?

**Comment by tdm** [comment]
No reply in over a week, assuming fixed or not reproducible.
