### ISSUE TITLE
Suggestion: LiveDisplay, shortcut in notifications.

### ISSUE THREAD

**Issue by EskeRahn** [tdm/android_device_fxtec_pro1#25]
I prefer "polar bear" white over blueish white.
And I can see that the "Night Light" in Lineage has been extended to the "LiveDisplay"

It would be nice if it could be accessed directly as a notification icon. Perhaps with the "Display modes" as a drop down similar to the WiFi and Location drop downs.

**Comment by Gigadoc2** [comment]
There is already a QuickTile for LiveDisplay, which allows you to toggle through the "day, night, automatic" and "bright sun" display modes. Is that what you are looking for or do you also want to toggle through the color spaces?

In any case, that should probably be a feature request with LineageOS in general, not only for this phone ;)

**Comment by EskeRahn** [comment]
Thanks for the hint. You are right it is general, Let us close this.
