### ISSUE TITLE
Notification LED and Vibrate Not Working

### ISSUE THREAD

**Issue by PolarisP1** [tdm/android_device_fxtec_pro1#26]
The vibration motor for notifications was working well in the stock ROM, but I can't get it to function in LOS w/o loading a 3rd party app.

The notification LED would stop working (on my phone) in the stock ROM until I factory reset.  It would then start working again, but stop some random time later (until another reset).  However, under LOS I don't have any LED functionality (except for while being charged), regardless of 3rd party apps or not.

**Comment by tdm** [comment]
Should be fixed in test9.

**Comment by tdm** [comment]
No response, marking fixed.
