### ISSUE TITLE
Fingerprint sensor loses data at reboot

### ISSUE THREAD

**Issue by tdm** [tdm/android_device_fxtec_pro1#3]
Some devices lose fingerprint data on reboot.  Some do not.  Need to investigate.

**Comment by steffenWi** [comment]
If the fingerprint is meant by this, it does not happen on my device. Rebooted and shutdown and started again several times and my thumb was still recognized. I do have the google apps package installed, maybe that makes a difference?

**Comment by tdm** [comment]
Fixed by deleting fingerprint persist data when framework fingerprint data does not exist (eg. after a wipe).
