### ISSUE TITLE
Crackle on Sound Effects

### ISSUE THREAD

**Issue by enigma9o7** [tdm/android_device_fxtec_pro1#33]
There is a crackle sound in most sound effects.

**Comment by EskeRahn** [comment]
In the stock it is mentioned that this is most likely a results of buffer underruns

**Comment by enigma9o7** [comment]
For some reason, it is possible to stop the audio crackle after it starts by plugging in or unplugging charger.   Have to do this every time you start a game that has the issue, and it immediately fixes it.  This workaround apparently doesn't work on stock, and not sure how long it's worked on lineage, but discovered around test8 time.

**Comment by tdm** [comment]
From the forum, this is reproducible by installing VLC and setting sound output to OpenSL ES.

**Comment by tdm** [comment]
Should be fixed in test10.

**Comment by tdm** [comment]
Verified fixed.
