### ISSUE TITLE
Language setting for physical keyboard is not applied correctly

### ISSUE THREAD

**Issue by steffenWi** [tdm/android_device_fxtec_pro1#4]
If you press "d" on the QWERTZ keyboard "s" appears. The numeric row is fine. I didn't try any special characters like äöü.

For stock Android the solution was to go to System, then "Language and Settings", then "Physical keyboard", then click "Fxtec Pro1 (Default)" and in the pop-up select "German" (Or Deutsch if your system is set to German). For stock android that allowed the keyboard to work. On Lineage that doesn't do anything as far as  I can tell.

**Comment by Loader009** [comment]
The german qwertz keyboard layout does not match the keyboard on the Pro1.
In theory those could/should be added to the vendor tree... but I have no idea about copyright stuff.

**Comment by Gigadoc2** [comment]
Isn't https://github.com/tdm/android_device_fxtec_pro1/pull/12 about adding those keymaps?

**Comment by Loader009** [comment]
You're right, https://github.com/tdm/android_device_fxtec_pro1/pull/12/commits/a56bda3c251bddf924a651c3ac194295d53acf58 should do it.

**Comment by CommanderStrax** [comment]
Still an issue with version 3. Setting german keyboard layout doesn't do anything.

**Comment by tdm** [comment]
Fixed in test6.  For now, you must set the keyboard layout as described here:

https://community.fxtec.com/topic/2509-lineageos-current-status-160-test-builds/?do=findComment&comment=44863

There will be a UI added before release.
