### ISSUE TITLE
test11 and test12 do not boot successfully after flashing.

### ISSUE THREAD

**Issue by schmittlauch** [tdm/android_device_fxtec_pro1#60]
I flashed the test11, test12 and test13 images on my Pro1.
After the test11 image still resulted in a successfully booting device, I rebooted back into the recovery to flash test12. The flashing itself was successful, but after a reboot the device did not boot properly and stayed at the boot animation for over 20 minutes until I finally shut it down. Flashing the test13 zip file from the recovery resulted in the same behaviour.

Before flashing I [reset my device to stock firmware](https://community.fxtec.com/topic/2466-guide-restore-to-stock-firmware-using-fastboot-method/). I strictly followed the instructions, tried the process using 2 different cables on 2 different USB2 ports on 2 different devices with 2 different OSes (NixOS, openSUSE) and 2 different platform-tools versions (28.0.1, 30.0.2).

Any idea what's going on? Is there a way I can provide boot logs?

**Comment by cameel** [comment]
Same here. I think this might have something to do with "Rebuild with latest Lineage tree" listed in changelog for version `test12`. The image is also became about 100 MB larger in that version.

**Comment by schmittlauch** [comment]
@cameel Just to check a theory of @tdm: Have yo flashed Sailfish OS before?

And did you just recently receive your phone or were you one of the early receivers?

**Comment by cameel** [comment]
I didn't. I have no interest in using Sailfish OS.

It's a very recent unit (number 7xx). My preorder was fulfilled just a few days ago.

**Comment by marmistrz** [comment]
I'm in a similar situation to @cameel. test10 works fine for me.

**Comment by rehejuhan** [comment]
Somewhat different situation here. "Old" device, S/N in the range 23X.
test11 boots successfully, all newer builds (currently up to 15) are resulting a non-booting situation. Also it is impossible to either boot test11 from another slot or to boot a fully functional recovery from either slots.

**Comment by rehejuhan** [comment]
https://community.fxtec.com/topic/2509-lineageos-current-status-160-test-builds/?do=findComment&comment=49172
test16 booted OK here

**Comment by marmistrz** [comment]
test16 works for me too!

**Comment by cameel** [comment]
Same here. I have just updated and it works perfectly. Also, it seems to have solved a small issue I had with switching physical keyboard layouts so that's great.

**Comment by Digital-Toxin** [comment]
This can be closed, Build 16 is confirmed to be bootable.

**Comment by tdm** [comment]
gapps was mistakenly included with these builds.
