### ISSUE TITLE
SELinux is deactivated

### ISSUE THREAD

**Issue by steffenWi** [tdm/android_device_fxtec_pro1#7]
This is bad and kinda important to fix as far as security goes.

**Comment by tdm** [comment]
This is true.  Please note that selinux is intentionally set to permissive for test builds.  It will be set to enforcing when we get closer to a stable build.

**Comment by steffenWi** [comment]
Ah, okay. In that case this can be closed :)

**Comment by tdm** [comment]
Reopening as a reminder.

**Comment by EskeRahn** [comment]
I guess this is also due to test build, so add it here as another reminder, on boot we get a warning:
"This build was signed with public keys"

**Comment by tdm** [comment]
Finally enforcing, yay!
