### ISSUE TITLE
FM radio app will not open

### ISSUE THREAD

**Issue by tdm** [tdm/android_device_fxtec_pro1#8]
Missing linkage to libfmjni.so.

**Comment by rhein** [comment]
When I do a LOS16 build based on this it actually fails, it only build successfully when I exclude the RMRadio Package via <remove-project name="LineageOS/android_packages_apps_FMRadio" />

Is this the same problem?

**Comment by Loader009** [comment]
Maybe because a flag is missing?
This one?
BOARD_HAVE_QCOM_FM
https://github.com/LineageOS/android_packages_apps_FMRadio/blob/lineage-17.1/jni/fmr/Android.mk#L15

**Comment by tdm** [comment]
Fixed in test11.
